name: flutter_native_image
description: A flutter plugin which uses native iOS/Android to resize, compress or crop
version: 0.0.6+1
homepage: https://konseben.dev
issue_tracker: https://github.com/btastic/flutter_native_image/issues

dependencies:
  flutter:
    sdk: flutter

environment:
  sdk: '>=2.12.0 <3.0.0'
  flutter: ">=1.10.0 <=2.2.0"

flutter:
  plugin:
    platforms:
      android:
        package: com.example.flutternativeimage
        pluginClass: FlutterNativeImagePlugin
      ios:
        package: com.example.flutternativeimage
        pluginClass: FlutterNativeImagePlugin
