name: flutter_native_image
description: A flutter plugin which uses native iOS/Android to resize, compress or crop
version: 0.0.5+3
homepage: https://konseben.dev

dependencies:
  flutter:
    sdk: flutter

environment:
  sdk: '>=1.19.0 <3.0.0'
  flutter: ">=1.10.0 <2.0.0"
  
flutter:
  plugin:
    platforms:
      android:
        package: com.example.flutternativeimage
        pluginClass: FlutterNativeImagePlugin
      ios:
        package: com.example.flutternativeimage
        pluginClass: FlutterNativeImagePlugin